/**
 * Theme presets.
 *
 * A theme is three sRGB channel triplets and nothing else. Everything the
 * interface does with colour — the accent ramp, the ambient washes, the
 * card sheen, the orb's glow, the focus ring, the selection colour — is
 * derived from those three values at runtime by `rgb(var(--accent-rgb) /
 * <alpha>)` in the stylesheet. That is why adding a theme here costs five
 * lines instead of an audit of every component.
 *
 * The palettes are hand-tuned rather than generated by rotating a hue.
 * A dark UI is unforgiving: an accent needs luminance above roughly 180
 * to read as light rather than as paint, and its hue has to survive being
 * rendered at 8% alpha over #07070a without going muddy. Automatic hue
 * rotation fails both tests, so these are picked by eye.
 */

export interface ThemePreset {
  id: string;
  label: string;
  /** One line describing the mood, shown under the swatch. */
  mood: string;
  /** Primary accent, as `R G B`. */
  accent: string;
  /** Secondary accent, used for `acting`, the horizon wash, and memory. */
  accent2: string;
}

export const THEME_PRESETS: readonly ThemePreset[] = [
  {
    id: "xana",
    label: "Xana",
    mood: "Signature cyan. Cool, precise, awake.",
    accent: "111 227 227",
    accent2: "156 140 255",
  },
  {
    id: "aurora",
    label: "Aurora",
    mood: "Mint and teal. Softer, a little closer to sleep.",
    accent: "125 232 191",
    accent2: "110 196 232",
  },
  {
    id: "ember",
    label: "Ember",
    mood: "Amber and clay. Warm, low, end-of-day.",
    accent: "240 178 122",
    accent2: "226 138 138",
  },
  {
    id: "lilac",
    label: "Lilac",
    mood: "Violet forward. Quieter, more interior.",
    accent: "175 158 252",
    accent2: "226 152 226",
  },
  {
    id: "signal",
    label: "Signal",
    mood: "High-contrast ice. Maximum legibility.",
    accent: "168 216 255",
    accent2: "200 200 235",
  },
  {
    id: "moss",
    label: "Moss",
    mood: "Green and mineral. Grounded, unhurried.",
    accent: "150 214 158",
    accent2: "176 206 168",
  },
] as const;

export const DEFAULT_THEME_ID = "xana";

export function findTheme(id: string): ThemePreset | undefined {
  return THEME_PRESETS.find((theme) => theme.id === id);
}

/**
 * `R G B` for a stored value, falling back to the default theme.
 * Returns the default rather than throwing: a hand-edited settings file
 * should cost a colour, not the app.
 */
export function safeAccent(value: string, fallbackIndex: 0 | 1): string {
  const parts = value.trim().split(/[\s,]+/).map(Number);
  if (parts.length !== 3) return defaultAccent(fallbackIndex);
  if (!parts.every((n) => Number.isInteger(n) && n >= 0 && n <= 255)) {
    return defaultAccent(fallbackIndex);
  }
  return parts.join(" ");
}

function defaultAccent(index: 0 | 1): string {
  const theme = THEME_PRESETS[0] as ThemePreset;
  return index === 0 ? theme.accent : theme.accent2;
}

/* ------------------------------------------------------------------ */
/* Contrast                                                           */
/* ------------------------------------------------------------------ */

function channels(value: string): [number, number, number] {
  const parts = value.trim().split(/[\s,]+/).map(Number);
  return [parts[0] ?? 0, parts[1] ?? 0, parts[2] ?? 0];
}

/** WCAG relative luminance. */
function luminance(rgb: readonly [number, number, number]): number {
  const [r, g, b] = rgb.map((v) => {
    const c = v / 255;
    return c <= 0.03928 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4);
  }) as [number, number, number];
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

/**
 * Contrast ratio between the accent and the void, as a plain number.
 *
 * Exposed because the custom-colour picker needs to warn: an accent dark
 * enough to be invisible against `#07070a` still produces a *valid*
 * theme, and the user should be told rather than left wondering why the
 * orb disappeared. The threshold in the UI is 3:1, which is the WCAG
 * minimum for a large graphical object.
 */
export function contrastWithVoid(value: string): number {
  const accentLum = luminance(channels(value));
  const voidLum = luminance([7, 7, 10]);
  const lighter = Math.max(accentLum, voidLum);
  const darker = Math.min(accentLum, voidLum);
  return (lighter + 0.05) / (darker + 0.05);
}
